using System;
using System.Collections.Generic;

namespace Lottery
{
    class LottoGame
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Please pick 6 unique numbers from 1-59");
            if (System.Diagnostics.Debugger.IsAttached) Console.ReadLine();
            Console.WriteLine("Press any key to start");
            Console.ReadLine();
            int[] pickedNumbers = new int[6];

            for (int i = 0; i < 6; i++)
            {
                Console.WriteLine("Please enter number");
                pickedNumbers[i] = Convert.ToInt32(Console.ReadLine());
            }
            
            string numbersStr = string.Join(",", pickedNumbers);
            Console.WriteLine("Thank you, your lottery numbers are {0}", numbersStr);
            Console.WriteLine("Press any key to start the draw, Good luck!");
            Console.ReadLine();
            int[] drawnNumbers = Draw();
            List<string> drawnStr = new List<string>();
            List<string> matchedNums = new List<string>();
            foreach (int number in drawnNumbers)
            {
                drawnStr.Add(number.ToString());
            }
            Console.WriteLine("The lottery numbers are {0}", string.Join(" ", drawnStr));

            Console.WriteLine(Compare(pickedNumbers, drawnNumbers));
        }


        // Generate and return 1 random number between 1 - 59
        private static int RandomNumber()
        {
            Random rand = new System.Random();
            int newRand = rand.Next(1, 60);
            return newRand;
        }


        // Fill and return array with 6 random numbers generated by RandomNumber()
        private static int[] Draw()
        {
            int[] winningNums = new int[6];
            for (int i = 0; i < 6; i++)
            {
                winningNums[i] = RandomNumber();
            }

            return winningNums;
        }


        // Compare pickedNumbers to drawnNumbers and return result message
        private static string Compare(int[] picked, int[] drawn)
        {
            string message;
            List<string> matchedNums = new List<string>();

            for (int i = 0; i < 6; i++)
            {
                for (int j = 0; j < 6; j++)
                {
                    if (picked[i] == drawn[j])
                    {
                        matchedNums.Add(picked[i].ToString());
                    }
                }
            }
            if (matchedNums.Count > 0 && matchedNums.Count < 6)
            {
                message = "Congratulations! you matched " + matchedNums.Count.ToString() + " numbers";
                message += " Your matched numbers are " + string.Join(" ", matchedNums);
            }
            else if (matchedNums.Count == 6)
            {
                message = "Congratulations you won the jackpot! You matched all 6 numbers";
            }
            else
            {
                message = "Unlucky! you didn't match any numbers. Try again";
            }

            return message;
        }

    }
}
